### ISSUE TITLE
Solid js update broke storeon (1.0.0 - 2021-06-27)

### ISSUE THREAD

**Issue by d0kur0** [storeon/solidjs#45]
Hello!

https://github.com/solidjs/solid/blob/main/CHANGELOG.md#100---2021-06-27

It says there: "**createState has been renamed to createStore and moved to solid-js/store. Also moved to solid-js/store: createMutable, produce, reconcile**"

Because of what the package no longer works:
![image](https://user-images.githubusercontent.com/31435565/137473827-5cd58cae-57ac-42a5-9c0b-c3d34ae682f9.png)

Will there be a fix? thanks

**Comment by distolma** [comment]
@d0kur0 Hi, thanks for the bug report.
Please, check v3.0.1, where I fixed it.
